SELECT IdServicio,FECHA,PEDIDO,CLIENTE,REFERENCIA_CLIENTE,AREA,GESTOR_RESPONSABLE,ORDEN ,
HORAS_CONTRATADAS,HORAS_ENTREGADAS,HORAS_DISPONIBLES 
FROM OrdenServicio WHERE ESTATUS='EN EJECUCION' AND HORAS_CONTRATADAS>0