//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReporteTareas.AD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://172.16.0.102/", ConfigurationName="AD.ActualizarCuentaAD")]
    public interface ActualizarCuentaAD {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento server del espacio de nombres http://172.16.0.102/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/ExtraerDatosUsuario", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/ExtraerDatosUsuarioResponse")]
        ReporteTareas.AD.ExtraerDatosUsuarioResponse ExtraerDatosUsuario(ReporteTareas.AD.ExtraerDatosUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/ExtraerDatosUsuario", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/ExtraerDatosUsuarioResponse")]
        System.Threading.Tasks.Task<ReporteTareas.AD.ExtraerDatosUsuarioResponse> ExtraerDatosUsuarioAsync(ReporteTareas.AD.ExtraerDatosUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento server del espacio de nombres http://172.16.0.102/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/CambiarContrasenia", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/CambiarContraseniaResponse")]
        ReporteTareas.AD.CambiarContraseniaResponse CambiarContrasenia(ReporteTareas.AD.CambiarContraseniaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/CambiarContrasenia", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/CambiarContraseniaResponse")]
        System.Threading.Tasks.Task<ReporteTareas.AD.CambiarContraseniaResponse> CambiarContraseniaAsync(ReporteTareas.AD.CambiarContraseniaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento server del espacio de nombres http://172.16.0.102/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/DesbloquearUsuario", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/DesbloquearUsuarioResponse")]
        ReporteTareas.AD.DesbloquearUsuarioResponse DesbloquearUsuario(ReporteTareas.AD.DesbloquearUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/DesbloquearUsuario", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/DesbloquearUsuarioResponse")]
        System.Threading.Tasks.Task<ReporteTareas.AD.DesbloquearUsuarioResponse> DesbloquearUsuarioAsync(ReporteTareas.AD.DesbloquearUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento server del espacio de nombres http://172.16.0.102/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/ValidarCuenta", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/ValidarCuentaResponse")]
        ReporteTareas.AD.ValidarCuentaResponse ValidarCuenta(ReporteTareas.AD.ValidarCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/ValidarCuenta", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/ValidarCuentaResponse")]
        System.Threading.Tasks.Task<ReporteTareas.AD.ValidarCuentaResponse> ValidarCuentaAsync(ReporteTareas.AD.ValidarCuentaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento server del espacio de nombres http://172.16.0.102/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/VerUsuario", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/VerUsuarioResponse")]
        ReporteTareas.AD.VerUsuarioResponse VerUsuario(ReporteTareas.AD.VerUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/VerUsuario", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/VerUsuarioResponse")]
        System.Threading.Tasks.Task<ReporteTareas.AD.VerUsuarioResponse> VerUsuarioAsync(ReporteTareas.AD.VerUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento server del espacio de nombres http://172.16.0.102/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/FechaCaducidad", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/FechaCaducidadResponse")]
        ReporteTareas.AD.FechaCaducidadResponse FechaCaducidad(ReporteTareas.AD.FechaCaducidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/FechaCaducidad", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/FechaCaducidadResponse")]
        System.Threading.Tasks.Task<ReporteTareas.AD.FechaCaducidadResponse> FechaCaducidadAsync(ReporteTareas.AD.FechaCaducidadRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento server del espacio de nombres http://172.16.0.102/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/GenerarUsuarios", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/GenerarUsuariosResponse")]
        ReporteTareas.AD.GenerarUsuariosResponse GenerarUsuarios(ReporteTareas.AD.GenerarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/GenerarUsuarios", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/GenerarUsuariosResponse")]
        System.Threading.Tasks.Task<ReporteTareas.AD.GenerarUsuariosResponse> GenerarUsuariosAsync(ReporteTareas.AD.GenerarUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento server del espacio de nombres http://172.16.0.102/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/ActualizarUsuarios", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/ActualizarUsuariosResponse")]
        ReporteTareas.AD.ActualizarUsuariosResponse ActualizarUsuarios(ReporteTareas.AD.ActualizarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/ActualizarUsuarios", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/ActualizarUsuariosResponse")]
        System.Threading.Tasks.Task<ReporteTareas.AD.ActualizarUsuariosResponse> ActualizarUsuariosAsync(ReporteTareas.AD.ActualizarUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento server del espacio de nombres http://172.16.0.102/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/ListarUsuarios", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/ListarUsuariosResponse")]
        ReporteTareas.AD.ListarUsuariosResponse ListarUsuarios(ReporteTareas.AD.ListarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/ListarUsuarios", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<ReporteTareas.AD.ListarUsuariosResponse> ListarUsuariosAsync(ReporteTareas.AD.ListarUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaUsuariosResult del espacio de nombres http://172.16.0.102/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/ListaUsuarios", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/ListaUsuariosResponse")]
        ReporteTareas.AD.ListaUsuariosResponse ListaUsuarios(ReporteTareas.AD.ListaUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.16.0.102/ActualizarCuentaAD/ListaUsuarios", ReplyAction="http://172.16.0.102/ActualizarCuentaAD/ListaUsuariosResponse")]
        System.Threading.Tasks.Task<ReporteTareas.AD.ListaUsuariosResponse> ListaUsuariosAsync(ReporteTareas.AD.ListaUsuariosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExtraerDatosUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExtraerDatosUsuario", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.ExtraerDatosUsuarioRequestBody Body;
        
        public ExtraerDatosUsuarioRequest() {
        }
        
        public ExtraerDatosUsuarioRequest(ReporteTareas.AD.ExtraerDatosUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class ExtraerDatosUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string server;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dominio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        public ExtraerDatosUsuarioRequestBody() {
        }
        
        public ExtraerDatosUsuarioRequestBody(string server, string dominio, string usuario, string password) {
            this.server = server;
            this.dominio = dominio;
            this.usuario = usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExtraerDatosUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExtraerDatosUsuarioResponse", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.ExtraerDatosUsuarioResponseBody Body;
        
        public ExtraerDatosUsuarioResponse() {
        }
        
        public ExtraerDatosUsuarioResponse(ReporteTareas.AD.ExtraerDatosUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class ExtraerDatosUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExtraerDatosUsuarioResult;
        
        public ExtraerDatosUsuarioResponseBody() {
        }
        
        public ExtraerDatosUsuarioResponseBody(string ExtraerDatosUsuarioResult) {
            this.ExtraerDatosUsuarioResult = ExtraerDatosUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarContraseniaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiarContrasenia", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.CambiarContraseniaRequestBody Body;
        
        public CambiarContraseniaRequest() {
        }
        
        public CambiarContraseniaRequest(ReporteTareas.AD.CambiarContraseniaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class CambiarContraseniaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string server;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dominio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Nuevopassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Confirpassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int EstadoProceso;
        
        public CambiarContraseniaRequestBody() {
        }
        
        public CambiarContraseniaRequestBody(string server, string dominio, string usuario, string password, string Nuevopassword, string Confirpassword, int EstadoProceso) {
            this.server = server;
            this.dominio = dominio;
            this.usuario = usuario;
            this.password = password;
            this.Nuevopassword = Nuevopassword;
            this.Confirpassword = Confirpassword;
            this.EstadoProceso = EstadoProceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarContraseniaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiarContraseniaResponse", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.CambiarContraseniaResponseBody Body;
        
        public CambiarContraseniaResponse() {
        }
        
        public CambiarContraseniaResponse(ReporteTareas.AD.CambiarContraseniaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class CambiarContraseniaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CambiarContraseniaResult;
        
        public CambiarContraseniaResponseBody() {
        }
        
        public CambiarContraseniaResponseBody(string CambiarContraseniaResult) {
            this.CambiarContraseniaResult = CambiarContraseniaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DesbloquearUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DesbloquearUsuario", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.DesbloquearUsuarioRequestBody Body;
        
        public DesbloquearUsuarioRequest() {
        }
        
        public DesbloquearUsuarioRequest(ReporteTareas.AD.DesbloquearUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class DesbloquearUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string server;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dominio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string datosUsuarios;
        
        public DesbloquearUsuarioRequestBody() {
        }
        
        public DesbloquearUsuarioRequestBody(string server, string dominio, string usuario, string password, string Carpeta, string datosUsuarios) {
            this.server = server;
            this.dominio = dominio;
            this.usuario = usuario;
            this.password = password;
            this.Carpeta = Carpeta;
            this.datosUsuarios = datosUsuarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DesbloquearUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DesbloquearUsuarioResponse", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.DesbloquearUsuarioResponseBody Body;
        
        public DesbloquearUsuarioResponse() {
        }
        
        public DesbloquearUsuarioResponse(ReporteTareas.AD.DesbloquearUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class DesbloquearUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DesbloquearUsuarioResult;
        
        public DesbloquearUsuarioResponseBody() {
        }
        
        public DesbloquearUsuarioResponseBody(string DesbloquearUsuarioResult) {
            this.DesbloquearUsuarioResult = DesbloquearUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCuenta", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.ValidarCuentaRequestBody Body;
        
        public ValidarCuentaRequest() {
        }
        
        public ValidarCuentaRequest(ReporteTareas.AD.ValidarCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class ValidarCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string server;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dominio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string datosUsuarios;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int EstadoProceso;
        
        public ValidarCuentaRequestBody() {
        }
        
        public ValidarCuentaRequestBody(string server, string dominio, string usuario, string password, string Carpeta, string datosUsuarios, int EstadoProceso) {
            this.server = server;
            this.dominio = dominio;
            this.usuario = usuario;
            this.password = password;
            this.Carpeta = Carpeta;
            this.datosUsuarios = datosUsuarios;
            this.EstadoProceso = EstadoProceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCuentaResponse", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.ValidarCuentaResponseBody Body;
        
        public ValidarCuentaResponse() {
        }
        
        public ValidarCuentaResponse(ReporteTareas.AD.ValidarCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class ValidarCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidarCuentaResult;
        
        public ValidarCuentaResponseBody() {
        }
        
        public ValidarCuentaResponseBody(string ValidarCuentaResult) {
            this.ValidarCuentaResult = ValidarCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerUsuario", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.VerUsuarioRequestBody Body;
        
        public VerUsuarioRequest() {
        }
        
        public VerUsuarioRequest(ReporteTareas.AD.VerUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class VerUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string server;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dominio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string datosUsuarios;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int EstadoProceso;
        
        public VerUsuarioRequestBody() {
        }
        
        public VerUsuarioRequestBody(string server, string dominio, string usuario, string password, string Carpeta, string datosUsuarios, int EstadoProceso) {
            this.server = server;
            this.dominio = dominio;
            this.usuario = usuario;
            this.password = password;
            this.Carpeta = Carpeta;
            this.datosUsuarios = datosUsuarios;
            this.EstadoProceso = EstadoProceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerUsuarioResponse", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.VerUsuarioResponseBody Body;
        
        public VerUsuarioResponse() {
        }
        
        public VerUsuarioResponse(ReporteTareas.AD.VerUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class VerUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerUsuarioResult;
        
        public VerUsuarioResponseBody() {
        }
        
        public VerUsuarioResponseBody(string VerUsuarioResult) {
            this.VerUsuarioResult = VerUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FechaCaducidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FechaCaducidad", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.FechaCaducidadRequestBody Body;
        
        public FechaCaducidadRequest() {
        }
        
        public FechaCaducidadRequest(ReporteTareas.AD.FechaCaducidadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class FechaCaducidadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string server;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dominio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        public FechaCaducidadRequestBody() {
        }
        
        public FechaCaducidadRequestBody(string server, string dominio, string usuario, string password) {
            this.server = server;
            this.dominio = dominio;
            this.usuario = usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FechaCaducidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FechaCaducidadResponse", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.FechaCaducidadResponseBody Body;
        
        public FechaCaducidadResponse() {
        }
        
        public FechaCaducidadResponse(ReporteTareas.AD.FechaCaducidadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class FechaCaducidadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FechaCaducidadResult;
        
        public FechaCaducidadResponseBody() {
        }
        
        public FechaCaducidadResponseBody(string FechaCaducidadResult) {
            this.FechaCaducidadResult = FechaCaducidadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarUsuarios", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.GenerarUsuariosRequestBody Body;
        
        public GenerarUsuariosRequest() {
        }
        
        public GenerarUsuariosRequest(ReporteTareas.AD.GenerarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class GenerarUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string server;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dominio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string datosUsuarios;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Carpeta;
        
        public GenerarUsuariosRequestBody() {
        }
        
        public GenerarUsuariosRequestBody(string server, string dominio, string usuario, string password, string datosUsuarios, string Carpeta) {
            this.server = server;
            this.dominio = dominio;
            this.usuario = usuario;
            this.password = password;
            this.datosUsuarios = datosUsuarios;
            this.Carpeta = Carpeta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarUsuariosResponse", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.GenerarUsuariosResponseBody Body;
        
        public GenerarUsuariosResponse() {
        }
        
        public GenerarUsuariosResponse(ReporteTareas.AD.GenerarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class GenerarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerarUsuariosResult;
        
        public GenerarUsuariosResponseBody() {
        }
        
        public GenerarUsuariosResponseBody(string GenerarUsuariosResult) {
            this.GenerarUsuariosResult = GenerarUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuarios", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.ActualizarUsuariosRequestBody Body;
        
        public ActualizarUsuariosRequest() {
        }
        
        public ActualizarUsuariosRequest(ReporteTareas.AD.ActualizarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class ActualizarUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string server;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dominio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string datosUsuarios;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int EstadoProceso;
        
        public ActualizarUsuariosRequestBody() {
        }
        
        public ActualizarUsuariosRequestBody(string server, string dominio, string usuario, string password, string datosUsuarios, string Carpeta, int EstadoProceso) {
            this.server = server;
            this.dominio = dominio;
            this.usuario = usuario;
            this.password = password;
            this.datosUsuarios = datosUsuarios;
            this.Carpeta = Carpeta;
            this.EstadoProceso = EstadoProceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuariosResponse", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.ActualizarUsuariosResponseBody Body;
        
        public ActualizarUsuariosResponse() {
        }
        
        public ActualizarUsuariosResponse(ReporteTareas.AD.ActualizarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class ActualizarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActualizarUsuariosResult;
        
        public ActualizarUsuariosResponseBody() {
        }
        
        public ActualizarUsuariosResponseBody(string ActualizarUsuariosResult) {
            this.ActualizarUsuariosResult = ActualizarUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarUsuarios", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.ListarUsuariosRequestBody Body;
        
        public ListarUsuariosRequest() {
        }
        
        public ListarUsuariosRequest(ReporteTareas.AD.ListarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class ListarUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string server;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dominio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int EstadoProceso;
        
        public ListarUsuariosRequestBody() {
        }
        
        public ListarUsuariosRequestBody(string server, string dominio, string usuario, string password, string Carpeta, int EstadoProceso) {
            this.server = server;
            this.dominio = dominio;
            this.usuario = usuario;
            this.password = password;
            this.Carpeta = Carpeta;
            this.EstadoProceso = EstadoProceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarUsuariosResponse", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.ListarUsuariosResponseBody Body;
        
        public ListarUsuariosResponse() {
        }
        
        public ListarUsuariosResponse(ReporteTareas.AD.ListarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class ListarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListarUsuariosResult;
        
        public ListarUsuariosResponseBody() {
        }
        
        public ListarUsuariosResponseBody(string ListarUsuariosResult) {
            this.ListarUsuariosResult = ListarUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaUsuarios", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.ListaUsuariosRequestBody Body;
        
        public ListaUsuariosRequest() {
        }
        
        public ListaUsuariosRequest(ReporteTareas.AD.ListaUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaUsuariosRequestBody {
        
        public ListaUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaUsuariosResponse", Namespace="http://172.16.0.102/", Order=0)]
        public ReporteTareas.AD.ListaUsuariosResponseBody Body;
        
        public ListaUsuariosResponse() {
        }
        
        public ListaUsuariosResponse(ReporteTareas.AD.ListaUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.16.0.102/")]
    public partial class ListaUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListaUsuariosResult;
        
        public ListaUsuariosResponseBody() {
        }
        
        public ListaUsuariosResponseBody(string ListaUsuariosResult) {
            this.ListaUsuariosResult = ListaUsuariosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActualizarCuentaADChannel : ReporteTareas.AD.ActualizarCuentaAD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActualizarCuentaADClient : System.ServiceModel.ClientBase<ReporteTareas.AD.ActualizarCuentaAD>, ReporteTareas.AD.ActualizarCuentaAD {
        
        public ActualizarCuentaADClient() {
        }
        
        public ActualizarCuentaADClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActualizarCuentaADClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActualizarCuentaADClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActualizarCuentaADClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.AD.ExtraerDatosUsuarioResponse ReporteTareas.AD.ActualizarCuentaAD.ExtraerDatosUsuario(ReporteTareas.AD.ExtraerDatosUsuarioRequest request) {
            return base.Channel.ExtraerDatosUsuario(request);
        }
        
        public string ExtraerDatosUsuario(string server, string dominio, string usuario, string password) {
            ReporteTareas.AD.ExtraerDatosUsuarioRequest inValue = new ReporteTareas.AD.ExtraerDatosUsuarioRequest();
            inValue.Body = new ReporteTareas.AD.ExtraerDatosUsuarioRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            ReporteTareas.AD.ExtraerDatosUsuarioResponse retVal = ((ReporteTareas.AD.ActualizarCuentaAD)(this)).ExtraerDatosUsuario(inValue);
            return retVal.Body.ExtraerDatosUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.AD.ExtraerDatosUsuarioResponse> ReporteTareas.AD.ActualizarCuentaAD.ExtraerDatosUsuarioAsync(ReporteTareas.AD.ExtraerDatosUsuarioRequest request) {
            return base.Channel.ExtraerDatosUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.AD.ExtraerDatosUsuarioResponse> ExtraerDatosUsuarioAsync(string server, string dominio, string usuario, string password) {
            ReporteTareas.AD.ExtraerDatosUsuarioRequest inValue = new ReporteTareas.AD.ExtraerDatosUsuarioRequest();
            inValue.Body = new ReporteTareas.AD.ExtraerDatosUsuarioRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            return ((ReporteTareas.AD.ActualizarCuentaAD)(this)).ExtraerDatosUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.AD.CambiarContraseniaResponse ReporteTareas.AD.ActualizarCuentaAD.CambiarContrasenia(ReporteTareas.AD.CambiarContraseniaRequest request) {
            return base.Channel.CambiarContrasenia(request);
        }
        
        public string CambiarContrasenia(string server, string dominio, string usuario, string password, string Nuevopassword, string Confirpassword, int EstadoProceso) {
            ReporteTareas.AD.CambiarContraseniaRequest inValue = new ReporteTareas.AD.CambiarContraseniaRequest();
            inValue.Body = new ReporteTareas.AD.CambiarContraseniaRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.Nuevopassword = Nuevopassword;
            inValue.Body.Confirpassword = Confirpassword;
            inValue.Body.EstadoProceso = EstadoProceso;
            ReporteTareas.AD.CambiarContraseniaResponse retVal = ((ReporteTareas.AD.ActualizarCuentaAD)(this)).CambiarContrasenia(inValue);
            return retVal.Body.CambiarContraseniaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.AD.CambiarContraseniaResponse> ReporteTareas.AD.ActualizarCuentaAD.CambiarContraseniaAsync(ReporteTareas.AD.CambiarContraseniaRequest request) {
            return base.Channel.CambiarContraseniaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.AD.CambiarContraseniaResponse> CambiarContraseniaAsync(string server, string dominio, string usuario, string password, string Nuevopassword, string Confirpassword, int EstadoProceso) {
            ReporteTareas.AD.CambiarContraseniaRequest inValue = new ReporteTareas.AD.CambiarContraseniaRequest();
            inValue.Body = new ReporteTareas.AD.CambiarContraseniaRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.Nuevopassword = Nuevopassword;
            inValue.Body.Confirpassword = Confirpassword;
            inValue.Body.EstadoProceso = EstadoProceso;
            return ((ReporteTareas.AD.ActualizarCuentaAD)(this)).CambiarContraseniaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.AD.DesbloquearUsuarioResponse ReporteTareas.AD.ActualizarCuentaAD.DesbloquearUsuario(ReporteTareas.AD.DesbloquearUsuarioRequest request) {
            return base.Channel.DesbloquearUsuario(request);
        }
        
        public string DesbloquearUsuario(string server, string dominio, string usuario, string password, string Carpeta, string datosUsuarios) {
            ReporteTareas.AD.DesbloquearUsuarioRequest inValue = new ReporteTareas.AD.DesbloquearUsuarioRequest();
            inValue.Body = new ReporteTareas.AD.DesbloquearUsuarioRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.Carpeta = Carpeta;
            inValue.Body.datosUsuarios = datosUsuarios;
            ReporteTareas.AD.DesbloquearUsuarioResponse retVal = ((ReporteTareas.AD.ActualizarCuentaAD)(this)).DesbloquearUsuario(inValue);
            return retVal.Body.DesbloquearUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.AD.DesbloquearUsuarioResponse> ReporteTareas.AD.ActualizarCuentaAD.DesbloquearUsuarioAsync(ReporteTareas.AD.DesbloquearUsuarioRequest request) {
            return base.Channel.DesbloquearUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.AD.DesbloquearUsuarioResponse> DesbloquearUsuarioAsync(string server, string dominio, string usuario, string password, string Carpeta, string datosUsuarios) {
            ReporteTareas.AD.DesbloquearUsuarioRequest inValue = new ReporteTareas.AD.DesbloquearUsuarioRequest();
            inValue.Body = new ReporteTareas.AD.DesbloquearUsuarioRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.Carpeta = Carpeta;
            inValue.Body.datosUsuarios = datosUsuarios;
            return ((ReporteTareas.AD.ActualizarCuentaAD)(this)).DesbloquearUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.AD.ValidarCuentaResponse ReporteTareas.AD.ActualizarCuentaAD.ValidarCuenta(ReporteTareas.AD.ValidarCuentaRequest request) {
            return base.Channel.ValidarCuenta(request);
        }
        
        public string ValidarCuenta(string server, string dominio, string usuario, string password, string Carpeta, string datosUsuarios, int EstadoProceso) {
            ReporteTareas.AD.ValidarCuentaRequest inValue = new ReporteTareas.AD.ValidarCuentaRequest();
            inValue.Body = new ReporteTareas.AD.ValidarCuentaRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.Carpeta = Carpeta;
            inValue.Body.datosUsuarios = datosUsuarios;
            inValue.Body.EstadoProceso = EstadoProceso;
            ReporteTareas.AD.ValidarCuentaResponse retVal = ((ReporteTareas.AD.ActualizarCuentaAD)(this)).ValidarCuenta(inValue);
            return retVal.Body.ValidarCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.AD.ValidarCuentaResponse> ReporteTareas.AD.ActualizarCuentaAD.ValidarCuentaAsync(ReporteTareas.AD.ValidarCuentaRequest request) {
            return base.Channel.ValidarCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.AD.ValidarCuentaResponse> ValidarCuentaAsync(string server, string dominio, string usuario, string password, string Carpeta, string datosUsuarios, int EstadoProceso) {
            ReporteTareas.AD.ValidarCuentaRequest inValue = new ReporteTareas.AD.ValidarCuentaRequest();
            inValue.Body = new ReporteTareas.AD.ValidarCuentaRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.Carpeta = Carpeta;
            inValue.Body.datosUsuarios = datosUsuarios;
            inValue.Body.EstadoProceso = EstadoProceso;
            return ((ReporteTareas.AD.ActualizarCuentaAD)(this)).ValidarCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.AD.VerUsuarioResponse ReporteTareas.AD.ActualizarCuentaAD.VerUsuario(ReporteTareas.AD.VerUsuarioRequest request) {
            return base.Channel.VerUsuario(request);
        }
        
        public string VerUsuario(string server, string dominio, string usuario, string password, string Carpeta, string datosUsuarios, int EstadoProceso) {
            ReporteTareas.AD.VerUsuarioRequest inValue = new ReporteTareas.AD.VerUsuarioRequest();
            inValue.Body = new ReporteTareas.AD.VerUsuarioRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.Carpeta = Carpeta;
            inValue.Body.datosUsuarios = datosUsuarios;
            inValue.Body.EstadoProceso = EstadoProceso;
            ReporteTareas.AD.VerUsuarioResponse retVal = ((ReporteTareas.AD.ActualizarCuentaAD)(this)).VerUsuario(inValue);
            return retVal.Body.VerUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.AD.VerUsuarioResponse> ReporteTareas.AD.ActualizarCuentaAD.VerUsuarioAsync(ReporteTareas.AD.VerUsuarioRequest request) {
            return base.Channel.VerUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.AD.VerUsuarioResponse> VerUsuarioAsync(string server, string dominio, string usuario, string password, string Carpeta, string datosUsuarios, int EstadoProceso) {
            ReporteTareas.AD.VerUsuarioRequest inValue = new ReporteTareas.AD.VerUsuarioRequest();
            inValue.Body = new ReporteTareas.AD.VerUsuarioRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.Carpeta = Carpeta;
            inValue.Body.datosUsuarios = datosUsuarios;
            inValue.Body.EstadoProceso = EstadoProceso;
            return ((ReporteTareas.AD.ActualizarCuentaAD)(this)).VerUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.AD.FechaCaducidadResponse ReporteTareas.AD.ActualizarCuentaAD.FechaCaducidad(ReporteTareas.AD.FechaCaducidadRequest request) {
            return base.Channel.FechaCaducidad(request);
        }
        
        public string FechaCaducidad(string server, string dominio, string usuario, string password) {
            ReporteTareas.AD.FechaCaducidadRequest inValue = new ReporteTareas.AD.FechaCaducidadRequest();
            inValue.Body = new ReporteTareas.AD.FechaCaducidadRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            ReporteTareas.AD.FechaCaducidadResponse retVal = ((ReporteTareas.AD.ActualizarCuentaAD)(this)).FechaCaducidad(inValue);
            return retVal.Body.FechaCaducidadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.AD.FechaCaducidadResponse> ReporteTareas.AD.ActualizarCuentaAD.FechaCaducidadAsync(ReporteTareas.AD.FechaCaducidadRequest request) {
            return base.Channel.FechaCaducidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.AD.FechaCaducidadResponse> FechaCaducidadAsync(string server, string dominio, string usuario, string password) {
            ReporteTareas.AD.FechaCaducidadRequest inValue = new ReporteTareas.AD.FechaCaducidadRequest();
            inValue.Body = new ReporteTareas.AD.FechaCaducidadRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            return ((ReporteTareas.AD.ActualizarCuentaAD)(this)).FechaCaducidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.AD.GenerarUsuariosResponse ReporteTareas.AD.ActualizarCuentaAD.GenerarUsuarios(ReporteTareas.AD.GenerarUsuariosRequest request) {
            return base.Channel.GenerarUsuarios(request);
        }
        
        public string GenerarUsuarios(string server, string dominio, string usuario, string password, string datosUsuarios, string Carpeta) {
            ReporteTareas.AD.GenerarUsuariosRequest inValue = new ReporteTareas.AD.GenerarUsuariosRequest();
            inValue.Body = new ReporteTareas.AD.GenerarUsuariosRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.datosUsuarios = datosUsuarios;
            inValue.Body.Carpeta = Carpeta;
            ReporteTareas.AD.GenerarUsuariosResponse retVal = ((ReporteTareas.AD.ActualizarCuentaAD)(this)).GenerarUsuarios(inValue);
            return retVal.Body.GenerarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.AD.GenerarUsuariosResponse> ReporteTareas.AD.ActualizarCuentaAD.GenerarUsuariosAsync(ReporteTareas.AD.GenerarUsuariosRequest request) {
            return base.Channel.GenerarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.AD.GenerarUsuariosResponse> GenerarUsuariosAsync(string server, string dominio, string usuario, string password, string datosUsuarios, string Carpeta) {
            ReporteTareas.AD.GenerarUsuariosRequest inValue = new ReporteTareas.AD.GenerarUsuariosRequest();
            inValue.Body = new ReporteTareas.AD.GenerarUsuariosRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.datosUsuarios = datosUsuarios;
            inValue.Body.Carpeta = Carpeta;
            return ((ReporteTareas.AD.ActualizarCuentaAD)(this)).GenerarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.AD.ActualizarUsuariosResponse ReporteTareas.AD.ActualizarCuentaAD.ActualizarUsuarios(ReporteTareas.AD.ActualizarUsuariosRequest request) {
            return base.Channel.ActualizarUsuarios(request);
        }
        
        public string ActualizarUsuarios(string server, string dominio, string usuario, string password, string datosUsuarios, string Carpeta, int EstadoProceso) {
            ReporteTareas.AD.ActualizarUsuariosRequest inValue = new ReporteTareas.AD.ActualizarUsuariosRequest();
            inValue.Body = new ReporteTareas.AD.ActualizarUsuariosRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.datosUsuarios = datosUsuarios;
            inValue.Body.Carpeta = Carpeta;
            inValue.Body.EstadoProceso = EstadoProceso;
            ReporteTareas.AD.ActualizarUsuariosResponse retVal = ((ReporteTareas.AD.ActualizarCuentaAD)(this)).ActualizarUsuarios(inValue);
            return retVal.Body.ActualizarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.AD.ActualizarUsuariosResponse> ReporteTareas.AD.ActualizarCuentaAD.ActualizarUsuariosAsync(ReporteTareas.AD.ActualizarUsuariosRequest request) {
            return base.Channel.ActualizarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.AD.ActualizarUsuariosResponse> ActualizarUsuariosAsync(string server, string dominio, string usuario, string password, string datosUsuarios, string Carpeta, int EstadoProceso) {
            ReporteTareas.AD.ActualizarUsuariosRequest inValue = new ReporteTareas.AD.ActualizarUsuariosRequest();
            inValue.Body = new ReporteTareas.AD.ActualizarUsuariosRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.datosUsuarios = datosUsuarios;
            inValue.Body.Carpeta = Carpeta;
            inValue.Body.EstadoProceso = EstadoProceso;
            return ((ReporteTareas.AD.ActualizarCuentaAD)(this)).ActualizarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.AD.ListarUsuariosResponse ReporteTareas.AD.ActualizarCuentaAD.ListarUsuarios(ReporteTareas.AD.ListarUsuariosRequest request) {
            return base.Channel.ListarUsuarios(request);
        }
        
        public string ListarUsuarios(string server, string dominio, string usuario, string password, string Carpeta, int EstadoProceso) {
            ReporteTareas.AD.ListarUsuariosRequest inValue = new ReporteTareas.AD.ListarUsuariosRequest();
            inValue.Body = new ReporteTareas.AD.ListarUsuariosRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.Carpeta = Carpeta;
            inValue.Body.EstadoProceso = EstadoProceso;
            ReporteTareas.AD.ListarUsuariosResponse retVal = ((ReporteTareas.AD.ActualizarCuentaAD)(this)).ListarUsuarios(inValue);
            return retVal.Body.ListarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.AD.ListarUsuariosResponse> ReporteTareas.AD.ActualizarCuentaAD.ListarUsuariosAsync(ReporteTareas.AD.ListarUsuariosRequest request) {
            return base.Channel.ListarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.AD.ListarUsuariosResponse> ListarUsuariosAsync(string server, string dominio, string usuario, string password, string Carpeta, int EstadoProceso) {
            ReporteTareas.AD.ListarUsuariosRequest inValue = new ReporteTareas.AD.ListarUsuariosRequest();
            inValue.Body = new ReporteTareas.AD.ListarUsuariosRequestBody();
            inValue.Body.server = server;
            inValue.Body.dominio = dominio;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.Carpeta = Carpeta;
            inValue.Body.EstadoProceso = EstadoProceso;
            return ((ReporteTareas.AD.ActualizarCuentaAD)(this)).ListarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.AD.ListaUsuariosResponse ReporteTareas.AD.ActualizarCuentaAD.ListaUsuarios(ReporteTareas.AD.ListaUsuariosRequest request) {
            return base.Channel.ListaUsuarios(request);
        }
        
        public string ListaUsuarios() {
            ReporteTareas.AD.ListaUsuariosRequest inValue = new ReporteTareas.AD.ListaUsuariosRequest();
            inValue.Body = new ReporteTareas.AD.ListaUsuariosRequestBody();
            ReporteTareas.AD.ListaUsuariosResponse retVal = ((ReporteTareas.AD.ActualizarCuentaAD)(this)).ListaUsuarios(inValue);
            return retVal.Body.ListaUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.AD.ListaUsuariosResponse> ReporteTareas.AD.ActualizarCuentaAD.ListaUsuariosAsync(ReporteTareas.AD.ListaUsuariosRequest request) {
            return base.Channel.ListaUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.AD.ListaUsuariosResponse> ListaUsuariosAsync() {
            ReporteTareas.AD.ListaUsuariosRequest inValue = new ReporteTareas.AD.ListaUsuariosRequest();
            inValue.Body = new ReporteTareas.AD.ListaUsuariosRequestBody();
            return ((ReporteTareas.AD.ActualizarCuentaAD)(this)).ListaUsuariosAsync(inValue);
        }
    }
}
