//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReporteTareas.Autentificacion2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://ArandaCMDBService.org/")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int IdField;
        
        private int ProfileIdField;
        
        private int RoleIdField;
        
        private int ActiveUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAssistantField;
        
        private System.Nullable<System.DateTime> PasswordChangeDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int ProfileId {
            get {
                return this.ProfileIdField;
            }
            set {
                if ((this.ProfileIdField.Equals(value) != true)) {
                    this.ProfileIdField = value;
                    this.RaisePropertyChanged("ProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int ActiveUser {
            get {
                return this.ActiveUserField;
            }
            set {
                if ((this.ActiveUserField.Equals(value) != true)) {
                    this.ActiveUserField = value;
                    this.RaisePropertyChanged("ActiveUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string EmailAssistant {
            get {
                return this.EmailAssistantField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAssistantField, value) != true)) {
                    this.EmailAssistantField = value;
                    this.RaisePropertyChanged("EmailAssistant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<System.DateTime> PasswordChangeDate {
            get {
                return this.PasswordChangeDateField;
            }
            set {
                if ((this.PasswordChangeDateField.Equals(value) != true)) {
                    this.PasswordChangeDateField = value;
                    this.RaisePropertyChanged("PasswordChangeDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://ArandaCMDBService.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LdapInfo", Namespace="http://ArandaCMDBService.org/")]
    [System.SerializableAttribute()]
    public partial class LdapInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserStringField;
        
        private int SecurityField;
        
        private int ConnectionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserString {
            get {
                return this.UserStringField;
            }
            set {
                if ((object.ReferenceEquals(this.UserStringField, value) != true)) {
                    this.UserStringField = value;
                    this.RaisePropertyChanged("UserString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Security {
            get {
                return this.SecurityField;
            }
            set {
                if ((this.SecurityField.Equals(value) != true)) {
                    this.SecurityField = value;
                    this.RaisePropertyChanged("Security");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ConnectionType {
            get {
                return this.ConnectionTypeField;
            }
            set {
                if ((this.ConnectionTypeField.Equals(value) != true)) {
                    this.ConnectionTypeField = value;
                    this.RaisePropertyChanged("ConnectionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ArandaCMDBService.org/", ConfigurationName="Autentificacion2.AuthenticationSoap")]
    public interface AuthenticationSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetUserbyIdResult del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/GetUserbyId", ReplyAction="*")]
        ReporteTareas.Autentificacion2.GetUserbyIdResponse GetUserbyId(ReporteTareas.Autentificacion2.GetUserbyIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/GetUserbyId", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.GetUserbyIdResponse> GetUserbyIdAsync(ReporteTareas.Autentificacion2.GetUserbyIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento userName del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/GetUserbyName", ReplyAction="*")]
        ReporteTareas.Autentificacion2.GetUserbyNameResponse GetUserbyName(ReporteTareas.Autentificacion2.GetUserbyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/GetUserbyName", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.GetUserbyNameResponse> GetUserbyNameAsync(ReporteTareas.Autentificacion2.GetUserbyNameRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento language del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUserLanguage", ReplyAction="*")]
        ReporteTareas.Autentificacion2.UpdateUserLanguageResponse UpdateUserLanguage(ReporteTareas.Autentificacion2.UpdateUserLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUserLanguage", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserLanguageResponse> UpdateUserLanguageAsync(ReporteTareas.Autentificacion2.UpdateUserLanguageRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento password del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUserPassword", ReplyAction="*")]
        ReporteTareas.Autentificacion2.UpdateUserPasswordResponse UpdateUserPassword(ReporteTareas.Autentificacion2.UpdateUserPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUserPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserPasswordResponse> UpdateUserPasswordAsync(ReporteTareas.Autentificacion2.UpdateUserPasswordRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUserEmail", ReplyAction="*")]
        ReporteTareas.Autentificacion2.UpdateUserEmailResponse UpdateUserEmail(ReporteTareas.Autentificacion2.UpdateUserEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUserEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserEmailResponse> UpdateUserEmailAsync(ReporteTareas.Autentificacion2.UpdateUserEmailRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUserName", ReplyAction="*")]
        ReporteTareas.Autentificacion2.UpdateUserNameResponse UpdateUserName(ReporteTareas.Autentificacion2.UpdateUserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserNameResponse> UpdateUserNameAsync(ReporteTareas.Autentificacion2.UpdateUserNameRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento item del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUser", ReplyAction="*")]
        ReporteTareas.Autentificacion2.UpdateUserResponse UpdateUser(ReporteTareas.Autentificacion2.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserResponse> UpdateUserAsync(ReporteTareas.Autentificacion2.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/ActivateUser", ReplyAction="*")]
        void ActivateUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/ActivateUser", ReplyAction="*")]
        System.Threading.Tasks.Task ActivateUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UnactivateUser", ReplyAction="*")]
        void UnactivateUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UnactivateUser", ReplyAction="*")]
        System.Threading.Tasks.Task UnactivateUserAsync(int userId);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento userName del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/AutenticateUserAD", ReplyAction="*")]
        ReporteTareas.Autentificacion2.AutenticateUserADResponse AutenticateUserAD(ReporteTareas.Autentificacion2.AutenticateUserADRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/AutenticateUserAD", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.AutenticateUserADResponse> AutenticateUserADAsync(ReporteTareas.Autentificacion2.AutenticateUserADRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetDomainsResult del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/GetDomains", ReplyAction="*")]
        ReporteTareas.Autentificacion2.GetDomainsResponse GetDomains(ReporteTareas.Autentificacion2.GetDomainsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/GetDomains", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.GetDomainsResponse> GetDomainsAsync(ReporteTareas.Autentificacion2.GetDomainsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento userName del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/AutenticateUserDB", ReplyAction="*")]
        ReporteTareas.Autentificacion2.AutenticateUserDBResponse AutenticateUserDB(ReporteTareas.Autentificacion2.AutenticateUserDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/AutenticateUserDB", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.AutenticateUserDBResponse> AutenticateUserDBAsync(ReporteTareas.Autentificacion2.AutenticateUserDBRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento userName del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/AutenticateUserDBEncrip", ReplyAction="*")]
        ReporteTareas.Autentificacion2.AutenticateUserDBEncripResponse AutenticateUserDBEncrip(ReporteTareas.Autentificacion2.AutenticateUserDBEncripRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/AutenticateUserDBEncrip", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.AutenticateUserDBEncripResponse> AutenticateUserDBEncripAsync(ReporteTareas.Autentificacion2.AutenticateUserDBEncripRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListServersResult del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/ListServers", ReplyAction="*")]
        ReporteTareas.Autentificacion2.ListServersResponse ListServers(ReporteTareas.Autentificacion2.ListServersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/ListServers", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.ListServersResponse> ListServersAsync(ReporteTareas.Autentificacion2.ListServersRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento userName del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/AutenticateUser", ReplyAction="*")]
        ReporteTareas.Autentificacion2.AutenticateUserResponse AutenticateUser(ReporteTareas.Autentificacion2.AutenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/AutenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.AutenticateUserResponse> AutenticateUserAsync(ReporteTareas.Autentificacion2.AutenticateUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento userName del espacio de nombres http://ArandaCMDBService.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/RememberPassword", ReplyAction="*")]
        ReporteTareas.Autentificacion2.RememberPasswordResponse RememberPassword(ReporteTareas.Autentificacion2.RememberPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/RememberPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.RememberPasswordResponse> RememberPasswordAsync(ReporteTareas.Autentificacion2.RememberPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserbyIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserbyId", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.GetUserbyIdRequestBody Body;
        
        public GetUserbyIdRequest() {
        }
        
        public GetUserbyIdRequest(ReporteTareas.Autentificacion2.GetUserbyIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class GetUserbyIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public GetUserbyIdRequestBody() {
        }
        
        public GetUserbyIdRequestBody(int userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserbyIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserbyIdResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.GetUserbyIdResponseBody Body;
        
        public GetUserbyIdResponse() {
        }
        
        public GetUserbyIdResponse(ReporteTareas.Autentificacion2.GetUserbyIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class GetUserbyIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReporteTareas.Autentificacion2.UserInfo GetUserbyIdResult;
        
        public GetUserbyIdResponseBody() {
        }
        
        public GetUserbyIdResponseBody(ReporteTareas.Autentificacion2.UserInfo GetUserbyIdResult) {
            this.GetUserbyIdResult = GetUserbyIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserbyNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserbyName", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.GetUserbyNameRequestBody Body;
        
        public GetUserbyNameRequest() {
        }
        
        public GetUserbyNameRequest(ReporteTareas.Autentificacion2.GetUserbyNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class GetUserbyNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetUserbyNameRequestBody() {
        }
        
        public GetUserbyNameRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserbyNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserbyNameResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.GetUserbyNameResponseBody Body;
        
        public GetUserbyNameResponse() {
        }
        
        public GetUserbyNameResponse(ReporteTareas.Autentificacion2.GetUserbyNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class GetUserbyNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReporteTareas.Autentificacion2.UserInfo GetUserbyNameResult;
        
        public GetUserbyNameResponseBody() {
        }
        
        public GetUserbyNameResponseBody(ReporteTareas.Autentificacion2.UserInfo GetUserbyNameResult) {
            this.GetUserbyNameResult = GetUserbyNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserLanguage", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.UpdateUserLanguageRequestBody Body;
        
        public UpdateUserLanguageRequest() {
        }
        
        public UpdateUserLanguageRequest(ReporteTareas.Autentificacion2.UpdateUserLanguageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class UpdateUserLanguageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string language;
        
        public UpdateUserLanguageRequestBody() {
        }
        
        public UpdateUserLanguageRequestBody(int userId, string language) {
            this.userId = userId;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserLanguageResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.UpdateUserLanguageResponseBody Body;
        
        public UpdateUserLanguageResponse() {
        }
        
        public UpdateUserLanguageResponse(ReporteTareas.Autentificacion2.UpdateUserLanguageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUserLanguageResponseBody {
        
        public UpdateUserLanguageResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserPassword", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.UpdateUserPasswordRequestBody Body;
        
        public UpdateUserPasswordRequest() {
        }
        
        public UpdateUserPasswordRequest(ReporteTareas.Autentificacion2.UpdateUserPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class UpdateUserPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string oldPassword;
        
        public UpdateUserPasswordRequestBody() {
        }
        
        public UpdateUserPasswordRequestBody(int userId, string password, string oldPassword) {
            this.userId = userId;
            this.password = password;
            this.oldPassword = oldPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserPasswordResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.UpdateUserPasswordResponseBody Body;
        
        public UpdateUserPasswordResponse() {
        }
        
        public UpdateUserPasswordResponse(ReporteTareas.Autentificacion2.UpdateUserPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class UpdateUserPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserPasswordResult;
        
        public UpdateUserPasswordResponseBody() {
        }
        
        public UpdateUserPasswordResponseBody(bool UpdateUserPasswordResult) {
            this.UpdateUserPasswordResult = UpdateUserPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserEmail", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.UpdateUserEmailRequestBody Body;
        
        public UpdateUserEmailRequest() {
        }
        
        public UpdateUserEmailRequest(ReporteTareas.Autentificacion2.UpdateUserEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class UpdateUserEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public UpdateUserEmailRequestBody() {
        }
        
        public UpdateUserEmailRequestBody(int userId, string email) {
            this.userId = userId;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserEmailResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.UpdateUserEmailResponseBody Body;
        
        public UpdateUserEmailResponse() {
        }
        
        public UpdateUserEmailResponse(ReporteTareas.Autentificacion2.UpdateUserEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUserEmailResponseBody {
        
        public UpdateUserEmailResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserName", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.UpdateUserNameRequestBody Body;
        
        public UpdateUserNameRequest() {
        }
        
        public UpdateUserNameRequest(ReporteTareas.Autentificacion2.UpdateUserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class UpdateUserNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public UpdateUserNameRequestBody() {
        }
        
        public UpdateUserNameRequestBody(int userId, string name) {
            this.userId = userId;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserNameResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.UpdateUserNameResponseBody Body;
        
        public UpdateUserNameResponse() {
        }
        
        public UpdateUserNameResponse(ReporteTareas.Autentificacion2.UpdateUserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUserNameResponseBody {
        
        public UpdateUserNameResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.UpdateUserRequestBody Body;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(ReporteTareas.Autentificacion2.UpdateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class UpdateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReporteTareas.Autentificacion2.UserInfo item;
        
        public UpdateUserRequestBody() {
        }
        
        public UpdateUserRequestBody(ReporteTareas.Autentificacion2.UserInfo item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.UpdateUserResponseBody Body;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(ReporteTareas.Autentificacion2.UpdateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUserResponseBody {
        
        public UpdateUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserADRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserAD", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.AutenticateUserADRequestBody Body;
        
        public AutenticateUserADRequest() {
        }
        
        public AutenticateUserADRequest(ReporteTareas.Autentificacion2.AutenticateUserADRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserADRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string domain;
        
        public AutenticateUserADRequestBody() {
        }
        
        public AutenticateUserADRequestBody(string userName, string password, string domain) {
            this.userName = userName;
            this.password = password;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserADResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserADResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.AutenticateUserADResponseBody Body;
        
        public AutenticateUserADResponse() {
        }
        
        public AutenticateUserADResponse(ReporteTareas.Autentificacion2.AutenticateUserADResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserADResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReporteTareas.Autentificacion2.UserInfo AutenticateUserADResult;
        
        public AutenticateUserADResponseBody() {
        }
        
        public AutenticateUserADResponseBody(ReporteTareas.Autentificacion2.UserInfo AutenticateUserADResult) {
            this.AutenticateUserADResult = AutenticateUserADResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomainsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomains", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.GetDomainsRequestBody Body;
        
        public GetDomainsRequest() {
        }
        
        public GetDomainsRequest(ReporteTareas.Autentificacion2.GetDomainsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDomainsRequestBody {
        
        public GetDomainsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomainsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomainsResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.GetDomainsResponseBody Body;
        
        public GetDomainsResponse() {
        }
        
        public GetDomainsResponse(ReporteTareas.Autentificacion2.GetDomainsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class GetDomainsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReporteTareas.Autentificacion2.ArrayOfString GetDomainsResult;
        
        public GetDomainsResponseBody() {
        }
        
        public GetDomainsResponseBody(ReporteTareas.Autentificacion2.ArrayOfString GetDomainsResult) {
            this.GetDomainsResult = GetDomainsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserDB", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.AutenticateUserDBRequestBody Body;
        
        public AutenticateUserDBRequest() {
        }
        
        public AutenticateUserDBRequest(ReporteTareas.Autentificacion2.AutenticateUserDBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserDBRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AutenticateUserDBRequestBody() {
        }
        
        public AutenticateUserDBRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserDBResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.AutenticateUserDBResponseBody Body;
        
        public AutenticateUserDBResponse() {
        }
        
        public AutenticateUserDBResponse(ReporteTareas.Autentificacion2.AutenticateUserDBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserDBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReporteTareas.Autentificacion2.UserInfo AutenticateUserDBResult;
        
        public AutenticateUserDBResponseBody() {
        }
        
        public AutenticateUserDBResponseBody(ReporteTareas.Autentificacion2.UserInfo AutenticateUserDBResult) {
            this.AutenticateUserDBResult = AutenticateUserDBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserDBEncripRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserDBEncrip", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.AutenticateUserDBEncripRequestBody Body;
        
        public AutenticateUserDBEncripRequest() {
        }
        
        public AutenticateUserDBEncripRequest(ReporteTareas.Autentificacion2.AutenticateUserDBEncripRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserDBEncripRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AutenticateUserDBEncripRequestBody() {
        }
        
        public AutenticateUserDBEncripRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserDBEncripResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserDBEncripResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.AutenticateUserDBEncripResponseBody Body;
        
        public AutenticateUserDBEncripResponse() {
        }
        
        public AutenticateUserDBEncripResponse(ReporteTareas.Autentificacion2.AutenticateUserDBEncripResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserDBEncripResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReporteTareas.Autentificacion2.UserInfo AutenticateUserDBEncripResult;
        
        public AutenticateUserDBEncripResponseBody() {
        }
        
        public AutenticateUserDBEncripResponseBody(ReporteTareas.Autentificacion2.UserInfo AutenticateUserDBEncripResult) {
            this.AutenticateUserDBEncripResult = AutenticateUserDBEncripResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListServersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListServers", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.ListServersRequestBody Body;
        
        public ListServersRequest() {
        }
        
        public ListServersRequest(ReporteTareas.Autentificacion2.ListServersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListServersRequestBody {
        
        public ListServersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListServersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListServersResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.ListServersResponseBody Body;
        
        public ListServersResponse() {
        }
        
        public ListServersResponse(ReporteTareas.Autentificacion2.ListServersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class ListServersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReporteTareas.Autentificacion2.LdapInfo[] ListServersResult;
        
        public ListServersResponseBody() {
        }
        
        public ListServersResponseBody(ReporteTareas.Autentificacion2.LdapInfo[] ListServersResult) {
            this.ListServersResult = ListServersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUser", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.AutenticateUserRequestBody Body;
        
        public AutenticateUserRequest() {
        }
        
        public AutenticateUserRequest(ReporteTareas.Autentificacion2.AutenticateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int serverId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public AutenticateUserRequestBody() {
        }
        
        public AutenticateUserRequestBody(int serverId, string userName, string password) {
            this.serverId = serverId;
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.AutenticateUserResponseBody Body;
        
        public AutenticateUserResponse() {
        }
        
        public AutenticateUserResponse(ReporteTareas.Autentificacion2.AutenticateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReporteTareas.Autentificacion2.UserInfo AutenticateUserResult;
        
        public AutenticateUserResponseBody() {
        }
        
        public AutenticateUserResponseBody(ReporteTareas.Autentificacion2.UserInfo AutenticateUserResult) {
            this.AutenticateUserResult = AutenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RememberPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RememberPassword", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.RememberPasswordRequestBody Body;
        
        public RememberPasswordRequest() {
        }
        
        public RememberPasswordRequest(ReporteTareas.Autentificacion2.RememberPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class RememberPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public RememberPasswordRequestBody() {
        }
        
        public RememberPasswordRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RememberPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RememberPasswordResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ReporteTareas.Autentificacion2.RememberPasswordResponseBody Body;
        
        public RememberPasswordResponse() {
        }
        
        public RememberPasswordResponse(ReporteTareas.Autentificacion2.RememberPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class RememberPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RememberPasswordResult;
        
        public RememberPasswordResponseBody() {
        }
        
        public RememberPasswordResponseBody(bool RememberPasswordResult) {
            this.RememberPasswordResult = RememberPasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationSoapChannel : ReporteTareas.Autentificacion2.AuthenticationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationSoapClient : System.ServiceModel.ClientBase<ReporteTareas.Autentificacion2.AuthenticationSoap>, ReporteTareas.Autentificacion2.AuthenticationSoap {
        
        public AuthenticationSoapClient() {
        }
        
        public AuthenticationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.GetUserbyIdResponse ReporteTareas.Autentificacion2.AuthenticationSoap.GetUserbyId(ReporteTareas.Autentificacion2.GetUserbyIdRequest request) {
            return base.Channel.GetUserbyId(request);
        }
        
        public ReporteTareas.Autentificacion2.UserInfo GetUserbyId(int userId) {
            ReporteTareas.Autentificacion2.GetUserbyIdRequest inValue = new ReporteTareas.Autentificacion2.GetUserbyIdRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.GetUserbyIdRequestBody();
            inValue.Body.userId = userId;
            ReporteTareas.Autentificacion2.GetUserbyIdResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).GetUserbyId(inValue);
            return retVal.Body.GetUserbyIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.GetUserbyIdResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.GetUserbyIdAsync(ReporteTareas.Autentificacion2.GetUserbyIdRequest request) {
            return base.Channel.GetUserbyIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.GetUserbyIdResponse> GetUserbyIdAsync(int userId) {
            ReporteTareas.Autentificacion2.GetUserbyIdRequest inValue = new ReporteTareas.Autentificacion2.GetUserbyIdRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.GetUserbyIdRequestBody();
            inValue.Body.userId = userId;
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).GetUserbyIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.GetUserbyNameResponse ReporteTareas.Autentificacion2.AuthenticationSoap.GetUserbyName(ReporteTareas.Autentificacion2.GetUserbyNameRequest request) {
            return base.Channel.GetUserbyName(request);
        }
        
        public ReporteTareas.Autentificacion2.UserInfo GetUserbyName(string userName) {
            ReporteTareas.Autentificacion2.GetUserbyNameRequest inValue = new ReporteTareas.Autentificacion2.GetUserbyNameRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.GetUserbyNameRequestBody();
            inValue.Body.userName = userName;
            ReporteTareas.Autentificacion2.GetUserbyNameResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).GetUserbyName(inValue);
            return retVal.Body.GetUserbyNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.GetUserbyNameResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.GetUserbyNameAsync(ReporteTareas.Autentificacion2.GetUserbyNameRequest request) {
            return base.Channel.GetUserbyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.GetUserbyNameResponse> GetUserbyNameAsync(string userName) {
            ReporteTareas.Autentificacion2.GetUserbyNameRequest inValue = new ReporteTareas.Autentificacion2.GetUserbyNameRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.GetUserbyNameRequestBody();
            inValue.Body.userName = userName;
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).GetUserbyNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.UpdateUserLanguageResponse ReporteTareas.Autentificacion2.AuthenticationSoap.UpdateUserLanguage(ReporteTareas.Autentificacion2.UpdateUserLanguageRequest request) {
            return base.Channel.UpdateUserLanguage(request);
        }
        
        public void UpdateUserLanguage(int userId, string language) {
            ReporteTareas.Autentificacion2.UpdateUserLanguageRequest inValue = new ReporteTareas.Autentificacion2.UpdateUserLanguageRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.UpdateUserLanguageRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.language = language;
            ReporteTareas.Autentificacion2.UpdateUserLanguageResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).UpdateUserLanguage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserLanguageResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.UpdateUserLanguageAsync(ReporteTareas.Autentificacion2.UpdateUserLanguageRequest request) {
            return base.Channel.UpdateUserLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserLanguageResponse> UpdateUserLanguageAsync(int userId, string language) {
            ReporteTareas.Autentificacion2.UpdateUserLanguageRequest inValue = new ReporteTareas.Autentificacion2.UpdateUserLanguageRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.UpdateUserLanguageRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.language = language;
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).UpdateUserLanguageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.UpdateUserPasswordResponse ReporteTareas.Autentificacion2.AuthenticationSoap.UpdateUserPassword(ReporteTareas.Autentificacion2.UpdateUserPasswordRequest request) {
            return base.Channel.UpdateUserPassword(request);
        }
        
        public bool UpdateUserPassword(int userId, string password, string oldPassword) {
            ReporteTareas.Autentificacion2.UpdateUserPasswordRequest inValue = new ReporteTareas.Autentificacion2.UpdateUserPasswordRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.UpdateUserPasswordRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.oldPassword = oldPassword;
            ReporteTareas.Autentificacion2.UpdateUserPasswordResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).UpdateUserPassword(inValue);
            return retVal.Body.UpdateUserPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserPasswordResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.UpdateUserPasswordAsync(ReporteTareas.Autentificacion2.UpdateUserPasswordRequest request) {
            return base.Channel.UpdateUserPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserPasswordResponse> UpdateUserPasswordAsync(int userId, string password, string oldPassword) {
            ReporteTareas.Autentificacion2.UpdateUserPasswordRequest inValue = new ReporteTareas.Autentificacion2.UpdateUserPasswordRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.UpdateUserPasswordRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.oldPassword = oldPassword;
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).UpdateUserPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.UpdateUserEmailResponse ReporteTareas.Autentificacion2.AuthenticationSoap.UpdateUserEmail(ReporteTareas.Autentificacion2.UpdateUserEmailRequest request) {
            return base.Channel.UpdateUserEmail(request);
        }
        
        public void UpdateUserEmail(int userId, string email) {
            ReporteTareas.Autentificacion2.UpdateUserEmailRequest inValue = new ReporteTareas.Autentificacion2.UpdateUserEmailRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.UpdateUserEmailRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.email = email;
            ReporteTareas.Autentificacion2.UpdateUserEmailResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).UpdateUserEmail(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserEmailResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.UpdateUserEmailAsync(ReporteTareas.Autentificacion2.UpdateUserEmailRequest request) {
            return base.Channel.UpdateUserEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserEmailResponse> UpdateUserEmailAsync(int userId, string email) {
            ReporteTareas.Autentificacion2.UpdateUserEmailRequest inValue = new ReporteTareas.Autentificacion2.UpdateUserEmailRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.UpdateUserEmailRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.email = email;
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).UpdateUserEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.UpdateUserNameResponse ReporteTareas.Autentificacion2.AuthenticationSoap.UpdateUserName(ReporteTareas.Autentificacion2.UpdateUserNameRequest request) {
            return base.Channel.UpdateUserName(request);
        }
        
        public void UpdateUserName(int userId, string name) {
            ReporteTareas.Autentificacion2.UpdateUserNameRequest inValue = new ReporteTareas.Autentificacion2.UpdateUserNameRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.UpdateUserNameRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.name = name;
            ReporteTareas.Autentificacion2.UpdateUserNameResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).UpdateUserName(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserNameResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.UpdateUserNameAsync(ReporteTareas.Autentificacion2.UpdateUserNameRequest request) {
            return base.Channel.UpdateUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserNameResponse> UpdateUserNameAsync(int userId, string name) {
            ReporteTareas.Autentificacion2.UpdateUserNameRequest inValue = new ReporteTareas.Autentificacion2.UpdateUserNameRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.UpdateUserNameRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.name = name;
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).UpdateUserNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.UpdateUserResponse ReporteTareas.Autentificacion2.AuthenticationSoap.UpdateUser(ReporteTareas.Autentificacion2.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public void UpdateUser(ReporteTareas.Autentificacion2.UserInfo item) {
            ReporteTareas.Autentificacion2.UpdateUserRequest inValue = new ReporteTareas.Autentificacion2.UpdateUserRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.UpdateUserRequestBody();
            inValue.Body.item = item;
            ReporteTareas.Autentificacion2.UpdateUserResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).UpdateUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.UpdateUserAsync(ReporteTareas.Autentificacion2.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.UpdateUserResponse> UpdateUserAsync(ReporteTareas.Autentificacion2.UserInfo item) {
            ReporteTareas.Autentificacion2.UpdateUserRequest inValue = new ReporteTareas.Autentificacion2.UpdateUserRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.UpdateUserRequestBody();
            inValue.Body.item = item;
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).UpdateUserAsync(inValue);
        }
        
        public void ActivateUser(int userId) {
            base.Channel.ActivateUser(userId);
        }
        
        public System.Threading.Tasks.Task ActivateUserAsync(int userId) {
            return base.Channel.ActivateUserAsync(userId);
        }
        
        public void UnactivateUser(int userId) {
            base.Channel.UnactivateUser(userId);
        }
        
        public System.Threading.Tasks.Task UnactivateUserAsync(int userId) {
            return base.Channel.UnactivateUserAsync(userId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.AutenticateUserADResponse ReporteTareas.Autentificacion2.AuthenticationSoap.AutenticateUserAD(ReporteTareas.Autentificacion2.AutenticateUserADRequest request) {
            return base.Channel.AutenticateUserAD(request);
        }
        
        public ReporteTareas.Autentificacion2.UserInfo AutenticateUserAD(string userName, string password, string domain) {
            ReporteTareas.Autentificacion2.AutenticateUserADRequest inValue = new ReporteTareas.Autentificacion2.AutenticateUserADRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.AutenticateUserADRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.domain = domain;
            ReporteTareas.Autentificacion2.AutenticateUserADResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).AutenticateUserAD(inValue);
            return retVal.Body.AutenticateUserADResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.AutenticateUserADResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.AutenticateUserADAsync(ReporteTareas.Autentificacion2.AutenticateUserADRequest request) {
            return base.Channel.AutenticateUserADAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.AutenticateUserADResponse> AutenticateUserADAsync(string userName, string password, string domain) {
            ReporteTareas.Autentificacion2.AutenticateUserADRequest inValue = new ReporteTareas.Autentificacion2.AutenticateUserADRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.AutenticateUserADRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.domain = domain;
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).AutenticateUserADAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.GetDomainsResponse ReporteTareas.Autentificacion2.AuthenticationSoap.GetDomains(ReporteTareas.Autentificacion2.GetDomainsRequest request) {
            return base.Channel.GetDomains(request);
        }
        
        public ReporteTareas.Autentificacion2.ArrayOfString GetDomains() {
            ReporteTareas.Autentificacion2.GetDomainsRequest inValue = new ReporteTareas.Autentificacion2.GetDomainsRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.GetDomainsRequestBody();
            ReporteTareas.Autentificacion2.GetDomainsResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).GetDomains(inValue);
            return retVal.Body.GetDomainsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.GetDomainsResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.GetDomainsAsync(ReporteTareas.Autentificacion2.GetDomainsRequest request) {
            return base.Channel.GetDomainsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.GetDomainsResponse> GetDomainsAsync() {
            ReporteTareas.Autentificacion2.GetDomainsRequest inValue = new ReporteTareas.Autentificacion2.GetDomainsRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.GetDomainsRequestBody();
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).GetDomainsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.AutenticateUserDBResponse ReporteTareas.Autentificacion2.AuthenticationSoap.AutenticateUserDB(ReporteTareas.Autentificacion2.AutenticateUserDBRequest request) {
            return base.Channel.AutenticateUserDB(request);
        }
        
        public ReporteTareas.Autentificacion2.UserInfo AutenticateUserDB(string userName, string password) {
            ReporteTareas.Autentificacion2.AutenticateUserDBRequest inValue = new ReporteTareas.Autentificacion2.AutenticateUserDBRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.AutenticateUserDBRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            ReporteTareas.Autentificacion2.AutenticateUserDBResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).AutenticateUserDB(inValue);
            return retVal.Body.AutenticateUserDBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.AutenticateUserDBResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.AutenticateUserDBAsync(ReporteTareas.Autentificacion2.AutenticateUserDBRequest request) {
            return base.Channel.AutenticateUserDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.AutenticateUserDBResponse> AutenticateUserDBAsync(string userName, string password) {
            ReporteTareas.Autentificacion2.AutenticateUserDBRequest inValue = new ReporteTareas.Autentificacion2.AutenticateUserDBRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.AutenticateUserDBRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).AutenticateUserDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.AutenticateUserDBEncripResponse ReporteTareas.Autentificacion2.AuthenticationSoap.AutenticateUserDBEncrip(ReporteTareas.Autentificacion2.AutenticateUserDBEncripRequest request) {
            return base.Channel.AutenticateUserDBEncrip(request);
        }
        
        public ReporteTareas.Autentificacion2.UserInfo AutenticateUserDBEncrip(string userName, string password) {
            ReporteTareas.Autentificacion2.AutenticateUserDBEncripRequest inValue = new ReporteTareas.Autentificacion2.AutenticateUserDBEncripRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.AutenticateUserDBEncripRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            ReporteTareas.Autentificacion2.AutenticateUserDBEncripResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).AutenticateUserDBEncrip(inValue);
            return retVal.Body.AutenticateUserDBEncripResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.AutenticateUserDBEncripResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.AutenticateUserDBEncripAsync(ReporteTareas.Autentificacion2.AutenticateUserDBEncripRequest request) {
            return base.Channel.AutenticateUserDBEncripAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.AutenticateUserDBEncripResponse> AutenticateUserDBEncripAsync(string userName, string password) {
            ReporteTareas.Autentificacion2.AutenticateUserDBEncripRequest inValue = new ReporteTareas.Autentificacion2.AutenticateUserDBEncripRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.AutenticateUserDBEncripRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).AutenticateUserDBEncripAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.ListServersResponse ReporteTareas.Autentificacion2.AuthenticationSoap.ListServers(ReporteTareas.Autentificacion2.ListServersRequest request) {
            return base.Channel.ListServers(request);
        }
        
        public ReporteTareas.Autentificacion2.LdapInfo[] ListServers() {
            ReporteTareas.Autentificacion2.ListServersRequest inValue = new ReporteTareas.Autentificacion2.ListServersRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.ListServersRequestBody();
            ReporteTareas.Autentificacion2.ListServersResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).ListServers(inValue);
            return retVal.Body.ListServersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.ListServersResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.ListServersAsync(ReporteTareas.Autentificacion2.ListServersRequest request) {
            return base.Channel.ListServersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.ListServersResponse> ListServersAsync() {
            ReporteTareas.Autentificacion2.ListServersRequest inValue = new ReporteTareas.Autentificacion2.ListServersRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.ListServersRequestBody();
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).ListServersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.AutenticateUserResponse ReporteTareas.Autentificacion2.AuthenticationSoap.AutenticateUser(ReporteTareas.Autentificacion2.AutenticateUserRequest request) {
            return base.Channel.AutenticateUser(request);
        }
        
        public ReporteTareas.Autentificacion2.UserInfo AutenticateUser(int serverId, string userName, string password) {
            ReporteTareas.Autentificacion2.AutenticateUserRequest inValue = new ReporteTareas.Autentificacion2.AutenticateUserRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.AutenticateUserRequestBody();
            inValue.Body.serverId = serverId;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            ReporteTareas.Autentificacion2.AutenticateUserResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).AutenticateUser(inValue);
            return retVal.Body.AutenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.AutenticateUserResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.AutenticateUserAsync(ReporteTareas.Autentificacion2.AutenticateUserRequest request) {
            return base.Channel.AutenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.AutenticateUserResponse> AutenticateUserAsync(int serverId, string userName, string password) {
            ReporteTareas.Autentificacion2.AutenticateUserRequest inValue = new ReporteTareas.Autentificacion2.AutenticateUserRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.AutenticateUserRequestBody();
            inValue.Body.serverId = serverId;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).AutenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReporteTareas.Autentificacion2.RememberPasswordResponse ReporteTareas.Autentificacion2.AuthenticationSoap.RememberPassword(ReporteTareas.Autentificacion2.RememberPasswordRequest request) {
            return base.Channel.RememberPassword(request);
        }
        
        public bool RememberPassword(string userName) {
            ReporteTareas.Autentificacion2.RememberPasswordRequest inValue = new ReporteTareas.Autentificacion2.RememberPasswordRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.RememberPasswordRequestBody();
            inValue.Body.userName = userName;
            ReporteTareas.Autentificacion2.RememberPasswordResponse retVal = ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).RememberPassword(inValue);
            return retVal.Body.RememberPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.RememberPasswordResponse> ReporteTareas.Autentificacion2.AuthenticationSoap.RememberPasswordAsync(ReporteTareas.Autentificacion2.RememberPasswordRequest request) {
            return base.Channel.RememberPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReporteTareas.Autentificacion2.RememberPasswordResponse> RememberPasswordAsync(string userName) {
            ReporteTareas.Autentificacion2.RememberPasswordRequest inValue = new ReporteTareas.Autentificacion2.RememberPasswordRequest();
            inValue.Body = new ReporteTareas.Autentificacion2.RememberPasswordRequestBody();
            inValue.Body.userName = userName;
            return ((ReporteTareas.Autentificacion2.AuthenticationSoap)(this)).RememberPasswordAsync(inValue);
        }
    }
}
