//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo lo genera una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReporteTareas.Formulario
{
    public partial class PerfilesPersonal
    {
        /// <summary>
        /// Control fichas.
        /// </summary>
        protected global::System.Web.UI.UserControl fichas;
    }
}
